#!/usr/bin/env bash
# configure new ubuntu machine with custom header

sudo apt-get -y update
sudo apt-get -y install nginx

echo "add_header X-Served-By $hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf

sudo systemctl reload nginx
