#!/usr/bin/env bash
# installs and configures HAproxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver web-01 100.25.47.145:80 check\n\tserver web-02 54.209.112.57:80 check" >> /etc/haproxy/haproxy.cfg'

sudo systemctl restart haproxy
