#!/usr/bin/env bash
# to make ssh-ing into servers easier

if [ -n "$1" ]; then
	server="$1"
else
	echo "Usage: ./ssh SERVER"
	exit 1
fi

if [ "$server" = 'web-01' ]; then
	IP="100.25.47.145"
elif [ "$server" = 'web-02' ]; then
	IP="54.209.112.57"
elif [ "$server" = 'lb-01' ]; then
	IP="100.25.136.188"
else
	echo "Error. Servers available: web-01, web-02, lb-01"
	exit 1
fi


key_path="~/.ssh/id_rsa"

ssh -i "$key_path" ubuntu@"$IP"
